/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Border: typeof import('./src/components/unload/border.vue')['default']
    Button: typeof import('./src/components/sh/button.vue')['default']
    Container: typeof import('./src/components/footer/container.vue')['default']
    Copyright: typeof import('./src/components/footer/copyright.vue')['default']
    Countdown: typeof import('./src/components/sh/countdown.vue')['default']
    DatePicker: typeof import('./src/components/sh/date-picker.vue')['default']
    Deallink: typeof import('./src/components/footer/deallink.vue')['default']
    Default: typeof import('./src/components/layout/default.vue')['default']
    Dialog: typeof import('./src/components/sh/dialog.vue')['default']
    FormItem: typeof import('./src/components/sh/form-item.vue')['default']
    Gift: typeof import('./src/components/vuex/gift.vue')['default']
    Image: typeof import('./src/components/sh/image.vue')['default']
    Input: typeof import('./src/components/sh/input.vue')['default']
    Introduce: typeof import('./src/components/home/introduce.vue')['default']
    Item: typeof import('./src/components/vuex/item.vue')['default']
    Link: typeof import('./src/components/home/link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleImage: typeof import('./src/components/sh/scale-image.vue')['default']
    Stepper: typeof import('./src/components/sh/stepper.vue')['default']
    Toast: typeof import('./src/components/sh/toast.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
